# Site settings
{% if page.language == 'he' %}
title: המכון לקיימות, סביבה ובריאות בנגב
email: RuthieB@clalit.org.il
description: ת.ד. 151 באר שבע 84101 ישראל
{% else %}
title: Negev Environmental Health and Sustainability Institute
email: RuthieB@clalit.org.il
description: P.O.Box 151 Be'er Sheva, 84101 Israel.
{% endif %}
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nehsi.org" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Assistant Professor"
excerpt_separator: "<!--more-->"

# Multiple languages
gems:           ['jekyll-multiple-languages']

languages:          ['en', 'he']

# If not config, the first of languages will be the default
language_default:   'en'

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
