# Site settings
title: Negev Environmental Health and Sustainability Institute
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Negev Environmental Health and Sustainability Institute website.
  We're AWESOME!!!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://vsevkayf.github.io/NEHSI/" # the base hostname & protocol for your site
twitter_username: 
github_username:  vsevkayf

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Assistant Professor"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
